#ifndef QTAVMEDIAPLAYER_GLOBAL_H
#define QTAVMEDIAPLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTAVMEDIAPLAYER_LIBRARY)
#  define QTAVMEDIAPLAYERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTAVMEDIAPLAYERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTAVMEDIAPLAYER_GLOBAL_H
